### ISSUE TITLE
Submit open message

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/photo-contest#2]
Submit are opened for 0 days or 72034 seconds if you're a robot.

**Comment by bsvobodny** [comment]
Yep,

what is the requirement for that ?

**Comment by Shuunen** [comment]
my bad it's correct :p 

![image](https://cloud.githubusercontent.com/assets/439158/22110248/49ba62a4-de5b-11e6-8556-6f974711593a.png)

not a bug :)

**Comment by bsvobodny** [comment]
We could display the hours: minutes intead of 0 days...

**Comment by Shuunen** [comment]
if days < 0 yes :)

**Comment by bsvobodny** [comment]
OK.
On my TODO list !
