### ISSUE TITLE
Close button position

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/photo-contest#4]
Weird to have it bottom left on modals :
![image](https://cloud.githubusercontent.com/assets/439158/22110146/f9a4851a-de5a-11e6-8b12-bb6fee67ec8a.png)

**Comment by bsvobodny** [comment]
It has been made like that.
Do you want it on the right top corner as usual ?

**Comment by Shuunen** [comment]
would be better I think, and save on right no ?
