### ISSUE TITLE
Login page on mobile

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/photo-contest#5]
Can be better

**Comment by bsvobodny** [comment]
What did you expect ?

**Comment by Shuunen** [comment]
this is how it looks like actually :

![image](https://cloud.githubusercontent.com/assets/439158/22113897/11c2107e-de68-11e6-9d49-3d3fc47314d8.png)

**Comment by bsvobodny** [comment]
Not on my Nexus 5... weird
